INSERT INTO `reviews` (
        `username`,
        `userprofile`,
        `reviewtext`,
        `category_cleanliness`,
        `category_accuracy`,
        `category_communication`,
        `category_location`,
        `category_checkin`,
        `category_value`,
        `posteddate`,
        `locationreviewed`
    )
VALUES (
        "Trevor",
        "Trevor Profile link",
        "This place was awesome. We had a lot of fun at local entertainment spots. Worth checking out.",
        5.0,
        4.7,
        4.9,
        5.0,
        4.7,
        4.8,
        "September 2020",
        2
    ),
    (
        "Rawrzor",
        "Rawrzor Profile link",
        "Meh, it was alright. Not much to do around the area. Place was kinda messy. Nice, friendly service and check-in",
        3.8,
        4.2,
        4.1,
        3.3,
        4.6,
        3.7,
        "June 2020",
        3
    ),
    (
        "Lauren",
        "Lauren Profile link",
        "This place was really neat. Had fun exploring the area. Friendly host.",
        5.0,
        4.7,
        4.9,
        5.0,
        4.7,
        4.8,
        "January 2020",
        2
    ),
    (
        "Gwendolyn Schultz",
        "Gwendolyn Schultz link",
        "I had called upon my friend Sherlock Holmes upon the second morning after Christmas, with the intention of wishing him the compliments of the season. He was lounging upon the sofa in a purple dressing-gown, a pipe-rack within his reach upon the right, and a pile of crumpled morning papers, evidently newly studied, near at hand. Beside the couch was a wooden chair, and on the angle of the back hung a very seedy and disreputable hard-felt hat, much the worse for wear, and cracked in several places. A lens and a forceps lying upon the seat of the chair suggested that the hat had been suspended in this manner for the purpose of examination.",
        3.25,
        4.13,
        4.13,
        3.14,
        3.41,
        3.64,
        "July 2020",
        5
    ),
    (
        "Braelyn Gibson",
        "Braelyn Gibson link",
        "Ulysses, Ulysses — Soaring through all the galaxies. In search of Earth, flying in to the night. Ulysses, Ulysses — Fighting evil and tyranny, with all his power, and with all of his might. Ulysses — no-one else can do the things you do. Ulysses — like a bolt of thunder from the blue. Ulysses — always fighting all the evil forces bringing peace and justice to all.",
        3.25,
        4.67,
        4.55,
        3.97,
        3.97,
        4.02,
        "April 2020",
        14
    ),
    (
        "Adam Burgess",
        "Adam Burgess link",
        "Mutley, you snickering, floppy eared hound. When courage is needed, you’re never around. Those medals you wear on your moth-eaten chest should be there for bungling at which you are best. So, stop that pigeon, stop that pigeon, stop that pigeon, stop that pigeon, stop that pigeon, stop that pigeon, stop that pigeon. Howwww! Nab him, jab him, tab him, grab him, stop that pigeon now.",
        3.25,
        3.97,
        4.57,
        3.14,
        4.55,
        3.87,
        "June 2020",
        5
    ),
    (
        "Tamia Mejia",
        "Tamia Mejia link",
        "Ye bilged on her anchor poop deck hang the jib coffer Sail ho Plate Fleet jolly boat barkadeer sheet. Gaff keelhaul cable sutler loot blow the man down crimp brigantine bowsprit Jolly Roger. Take a caulk scurvy coffer lugger run a shot across the bow landlubber or just lubber bring a spring upon her cable jolly boat boatswain bucko.",
        4.55,
        4.57,
        4.62,
        4.5,
        3.57,
        4.13,
        "October 2020",
        18
    ),
    (
        "Teagan Briggs",
        "Teagan Briggs link",
        "Ye bilged on her anchor poop deck hang the jib coffer Sail ho Plate Fleet jolly boat barkadeer sheet. Gaff keelhaul cable sutler loot blow the man down crimp brigantine bowsprit Jolly Roger. Take a caulk scurvy coffer lugger run a shot across the bow landlubber or just lubber bring a spring upon her cable jolly boat boatswain bucko.",
        3.97,
        3.1,
        3.64,
        4.03,
        4.67,
        4.83,
        "June 2020",
        13
    ),
    (
        "Marley Estes",
        "Marley Estes link",
        "Kid, I've flown from one side of this galaxy to the other. I've seen a lot of strange stuff, but I've never seen anything to make me believe there's one all-powerful Force controlling everything. There's no mystical energy field that controls my destiny. It's all a lot of simple tricks and nonsense. Kid, I've flown from one side of this galaxy to the other. I've seen a lot of strange stuff, but I've never seen anything to make me believe there's one all-powerful Force controlling everything. There's no mystical energy field that controls my destiny. It's all a lot of simple tricks and nonsense.",
        4.57,
        4.5,
        4.62,
        3.73,
        3.1,
        3.64,
        "June 2020",
        7
    ),
    (
        "Tamia Mejia",
        "Tamia Mejia link",
        "Barnaby The Bear’s my name, never call me Jack or James, I will sing my way to fame, Barnaby the Bear’s my name. Birds taught me to sing, when they took me to their king, first I had to fly, in the sky so high so high, so high so high so high, so — if you want to sing this way, think of what you’d like to say, add a tune and you will see, just how easy it can be. Treacle pudding, fish and chips, fizzy drinks and liquorice, flowers, rivers, sand and sea, snowflakes and the stars are free.",
        4.02,
        3.96,
        4.26,
        3.97,
        4.13,
        4.57,
        "January 2020",
        15
    ),
    (
        "Adam Burgess",
        "Adam Burgess link",
        "Knight Rider, a shadowy flight into the dangerous world of a man who does not exist. Michael Knight, a young loner on a crusade to champion the cause of the innocent, the helpless in a world of criminals who operate above the law.",
        3.25,
        3.07,
        4.62,
        3.57,
        3.14,
        3.73,
        "May 2020",
        12
    ),
    (
        "Tyrell Burns",
        "Tyrell Burns link",
        "Cheese slices stinking bishop everyone loves. Everyone loves lancashire fromage boursin say cheese cheese triangles edam feta. Edam feta cut the cheese caerphilly the big cheese red leicester airedale edam. Mozzarella emmental ricotta fromage frais emmental cheeseburger fromage.",
        4.03,
        3.96,
        4.62,
        3.73,
        4.03,
        3.59,
        "December 2020",
        6
    ),
    (
        "Jazmyn Peterson",
        "Jazmyn Peterson link",
        "Kid, I've flown from one side of this galaxy to the other. I've seen a lot of strange stuff, but I've never seen anything to make me believe there's one all-powerful Force controlling everything. There's no mystical energy field that controls my destiny. It's all a lot of simple tricks and nonsense. Kid, I've flown from one side of this galaxy to the other. I've seen a lot of strange stuff, but I've never seen anything to make me believe there's one all-powerful Force controlling everything. There's no mystical energy field that controls my destiny. It's all a lot of simple tricks and nonsense.",
        3.91,
        3.41,
        3.25,
        3.07,
        4.63,
        4.55,
        "November 2020",
        13
    ),
    (
        "Jazmyn Peterson",
        "Jazmyn Peterson link",
        "Pepper jack smelly cheese monterey jack. Feta cottage cheese paneer roquefort cheddar bocconcini cheesy feet pecorino. Mozzarella cow cheesecake cheddar st. agur blue cheese danish fontina cream cheese cheese on toast. Manchego say cheese cottage cheese cottage cheese taleggio cheese triangles.",
        3.64,
        3.25,
        3.57,
        3.1,
        4.13,
        4.67,
        "November 2020",
        4
    ),
    (
        "Billy Fox",
        "Billy Fox link",
        "Eu exercitation culpa deserunt. Tri-tip capicola sirloin reprehenderit biltong, chuck hamburger ullamco boudin exercitation pork belly laboris buffalo sint bresaola. Nostrud chuck turducken, t-bone bresaola alcatra shoulder. Nostrud cupidatat porchetta sint, meatball officia capicola est commodo ham hock deserunt ullamco irure cow. Picanha nostrud id, in deserunt capicola adipisicing excepteur pancetta magna in turducken consequat ball tip.",
        4.55,
        4.26,
        3.99,
        3.41,
        3.91,
        4.57,
        "November 2020",
        3
    ),
    (
        "Demarion Munoz",
        "Demarion Munoz link",
        "Stop talking, brain thinking. Hush. Aw, you're all Mr. Grumpy Face today. All I've got to do is pass as an ordinary human being. Simple. What could possibly go wrong? I'm the Doctor. Well, they call me the Doctor. I don't know why. I call me the Doctor too. I still don't know why.",
        3.73,
        4.5,
        4.62,
        3.87,
        4.03,
        4.5,
        "March 2020",
        14
    ),
    (
        "Jaylin Ruiz",
        "Jaylin Ruiz link",
        "There’s a voice that keeps on calling me. Down the road, that’s where I’ll always be. Every stop I make, I make a new friend. Can’t stay for long, just turn around and I’m gone again. Maybe tomorrow, I’ll want to settle down, Until tomorrow, I’ll just keep moving on.",
        4.02,
        3.59,
        4.02,
        3.96,
        3.1,
        4.83,
        "May 2020",
        4
    ),
    (
        "Xander Mccann",
        "Xander Mccann link",
        "Knight Rider, a shadowy flight into the dangerous world of a man who does not exist. Michael Knight, a young loner on a crusade to champion the cause of the innocent, the helpless in a world of criminals who operate above the law.",
        3.64,
        3.64,
        3.07,
        4.83,
        4.62,
        4.63,
        "February 2020",
        8
    ),
    (
        "Billy Fox",
        "Billy Fox link",
        "Pommy ipsum bog off mush, apple and pears laughing gear. Bad Wolf one off Shakespeare made a pig's ear of it the dog's dinner fish and chips absobloodylootely, they can sod off a bit miffed conked him one on the nose it's me peepers see a man about a dog blimey is she 'avin a laugh, crumpets have a butcher's at this a cracking fork out absolute. Tally-ho well fit Northeners twiglets grub's up what a load of guff spend a penny, a right toff pork dripping cockney cup of tea. Jolly good odds and sods ponce upper class got a lot of brass gob hedgehog double dutch, ponce hedgehog fancy a cuppa spiffing throw a paddy cockney.",
        4.02,
        4.63,
        3.64,
        3.41,
        3.1,
        3.91,
        "July 2020",
        15
    ),
    (
        "Reese Bautista",
        "Reese Bautista link",
        "Beetroot water spinach okra water chestnut ricebean pea catsear courgette summer purslane. Water spinach arugula pea tatsoi aubergine spring onion bush tomato kale radicchio turnip chicory salsify pea sprouts fava bean. Dandelion zucchini burdock yarrow chickpea dandelion sorrel courgette turnip greens tigernut soybean radish artichoke wattle seed endive groundnut broccoli arugula.",
        3.25,
        3.96,
        4.67,
        3.07,
        3.25,
        4.63,
        "May 2020",
        8
    ),
    (
        "Jazmyn Peterson",
        "Jazmyn Peterson link",
        "Barnaby The Bear’s my name, never call me Jack or James, I will sing my way to fame, Barnaby the Bear’s my name. Birds taught me to sing, when they took me to their king, first I had to fly, in the sky so high so high, so high so high so high, so — if you want to sing this way, think of what you’d like to say, add a tune and you will see, just how easy it can be. Treacle pudding, fish and chips, fizzy drinks and liquorice, flowers, rivers, sand and sea, snowflakes and the stars are free.",
        3.25,
        4.57,
        3.1,
        3.87,
        3.25,
        4.13,
        "September 2020",
        4
    ),
    (
        "Tamia Mejia",
        "Tamia Mejia link",
        "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nullam feugiat, turpis at pulvinar vulputate, erat libero tristique tellus, nec bibendum odio risus sit amet ante. Aliquam erat volutpat. Nunc auctor. Mauris pretium quam et urna. Fusce nibh. Duis risus. Curabitur sagittis hendrerit ante. Aliquam erat volutpat. Vestibulum erat nulla, ullamcorper nec, rutrum non, nonummy ac, erat. Duis condimentum augue id magna semper rutrum. Nullam justo enim, consectetuer nec, ullamcorper ac, vestibulum in, elit. Proin pede metus, vulputate nec, fermentum fringilla, vehicula vitae, justo. Fusce consectetuer risus a nunc. Aliquam ornare wisi eu metus. Integer pellentesque quam vel velit. Duis pulvinar.",
        4.57,
        4.03,
        3.96,
        3.97,
        4.57,
        4.03,
        "October 2020",
        18
    ),
    (
        "Elaine Bauer",
        "Elaine Bauer link",
        "Boom grapple parrel fire in the hole Sink me fluke ye jury mast spanker gangplank. Weigh anchor belaying pin log list topgallant grapple code of conduct rutters Chain Shot hang the jib. Me lee squiffy rum rutters yardarm Gold Road Barbary Coast carouser Plate Fleet.",
        4.26,
        4.62,
        4.62,
        4.13,
        3.87,
        3.64,
        "January 2020",
        13
    ),
    (
        "Teagan Briggs",
        "Teagan Briggs link",
        "Beetroot water spinach okra water chestnut ricebean pea catsear courgette summer purslane. Water spinach arugula pea tatsoi aubergine spring onion bush tomato kale radicchio turnip chicory salsify pea sprouts fava bean. Dandelion zucchini burdock yarrow chickpea dandelion sorrel courgette turnip greens tigernut soybean radish artichoke wattle seed endive groundnut broccoli arugula.",
        4.62,
        3.14,
        3.91,
        3.96,
        3.14,
        3.07,
        "November 2020",
        14
    ),
    (
        "Elaine Bauer",
        "Elaine Bauer link",
        "80 days around the world, we’ll find a pot of gold just sitting where the rainbow’s ending. Time — we’ll fight against the time, and we’ll fly on the white wings of the wind. 80 days around the world, no we won’t say a word before the ship is really back. Round, round, all around the world. Round, all around the world. Round, all around the world. Round, all around the world.",
        4.26,
        3.41,
        4.83,
        3.59,
        4.03,
        3.97,
        "August 2020",
        17
    ),
    (
        "Xander Mccann",
        "Xander Mccann link",
        "There’s a voice that keeps on calling me. Down the road, that’s where I’ll always be. Every stop I make, I make a new friend. Can’t stay for long, just turn around and I’m gone again. Maybe tomorrow, I’ll want to settle down, Until tomorrow, I’ll just keep moving on.",
        3.07,
        3.91,
        3.91,
        3.97,
        3.73,
        4.03,
        "September 2020",
        11
    ),
    (
        "Gwendolyn Schultz",
        "Gwendolyn Schultz link",
        "I had called upon my friend Sherlock Holmes upon the second morning after Christmas, with the intention of wishing him the compliments of the season. He was lounging upon the sofa in a purple dressing-gown, a pipe-rack within his reach upon the right, and a pile of crumpled morning papers, evidently newly studied, near at hand. Beside the couch was a wooden chair, and on the angle of the back hung a very seedy and disreputable hard-felt hat, much the worse for wear, and cracked in several places. A lens and a forceps lying upon the seat of the chair suggested that the hat had been suspended in this manner for the purpose of examination.",
        4.5,
        3.99,
        3.99,
        3.1,
        4.02,
        4.03,
        "December 2020",
        18
    ),
    (
        "Ellie Gregory",
        "Ellie Gregory link",
        "I had called upon my friend Sherlock Holmes upon the second morning after Christmas, with the intention of wishing him the compliments of the season. He was lounging upon the sofa in a purple dressing-gown, a pipe-rack within his reach upon the right, and a pile of crumpled morning papers, evidently newly studied, near at hand. Beside the couch was a wooden chair, and on the angle of the back hung a very seedy and disreputable hard-felt hat, much the worse for wear, and cracked in several places. A lens and a forceps lying upon the seat of the chair suggested that the hat had been suspended in this manner for the purpose of examination.",
        3.57,
        3.64,
        3.73,
        3.91,
        4.63,
        4.55,
        "February 2020",
        11
    ),
    (
        "Braylen Noble",
        "Braylen Noble link",
        "Esse deserunt shoulder t-bone. Non in qui bacon ipsum pastrami. Shankle lorem labore pork loin aliquip beef laboris ea qui jerky. Eu nostrud fatback meatloaf, burgdoggen pastrami drumstick elit lorem consequat ipsum. Pancetta sausage dolor cupidatat rump adipisicing pariatur burgdoggen voluptate aliqua.",
        3.14,
        3.14,
        3.91,
        3.25,
        4.26,
        4.63,
        "June 2020",
        15
    ),
    (
        "Jaylin Ruiz",
        "Jaylin Ruiz link",
        "There’s a voice that keeps on calling me. Down the road, that’s where I’ll always be. Every stop I make, I make a new friend. Can’t stay for long, just turn around and I’m gone again. Maybe tomorrow, I’ll want to settle down, Until tomorrow, I’ll just keep moving on.",
        3.1,
        4.13,
        4.26,
        4.83,
        4.26,
        3.87,
        "August 2020",
        4
    ),
    (
        "Emmy Armstrong",
        "Emmy Armstrong link",
        "Gumbo beet greens corn soko endive gumbo gourd. Parsley shallot courgette tatsoi pea sprouts fava bean collard greens dandelion okra wakame tomato. Dandelion cucumber earthnut pea peanut soko zucchini.",
        3.14,
        3.73,
        3.99,
        3.96,
        4.67,
        3.25,
        "March 2020",
        8
    ),
    (
        "Tyrell Burns",
        "Tyrell Burns link",
        "Gumbo beet greens corn soko endive gumbo gourd. Parsley shallot courgette tatsoi pea sprouts fava bean collard greens dandelion okra wakame tomato. Dandelion cucumber earthnut pea peanut soko zucchini.",
        3.25,
        3.73,
        3.73,
        3.57,
        3.1,
        4.83,
        "August 2020",
        8
    ),
    (
        "Teagan Briggs",
        "Teagan Briggs link",
        "Morbi a metus. Phasellus enim erat, vestibulum vel, aliquam a, posuere eu, velit. Nullam sapien sem, ornare ac, nonummy non, lobortis a, enim. Nunc tincidunt ante vitae massa. Duis ante orci, molestie vitae, vehicula venenatis, tincidunt ac, pede. Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Etiam commodo dui eget wisi. Donec iaculis gravida nulla. Donec quis nibh at felis congue commodo. Etiam bibendum elit eget erat.",
        4.63,
        3.25,
        3.87,
        4.62,
        3.59,
        4.03,
        "January 2020",
        13
    ),
    (
        "Reagan Boyer",
        "Reagan Boyer link",
        "Pommy ipsum bog off mush, apple and pears laughing gear. Bad Wolf one off Shakespeare made a pig's ear of it the dog's dinner fish and chips absobloodylootely, they can sod off a bit miffed conked him one on the nose it's me peepers see a man about a dog blimey is she 'avin a laugh, crumpets have a butcher's at this a cracking fork out absolute. Tally-ho well fit Northeners twiglets grub's up what a load of guff spend a penny, a right toff pork dripping cockney cup of tea. Jolly good odds and sods ponce upper class got a lot of brass gob hedgehog double dutch, ponce hedgehog fancy a cuppa spiffing throw a paddy cockney.",
        3.25,
        3.73,
        3.14,
        4.67,
        4.67,
        3.97,
        "April 2020",
        18
    ),
    (
        "Marley Estes",
        "Marley Estes link",
        "Ye bilged on her anchor poop deck hang the jib coffer Sail ho Plate Fleet jolly boat barkadeer sheet. Gaff keelhaul cable sutler loot blow the man down crimp brigantine bowsprit Jolly Roger. Take a caulk scurvy coffer lugger run a shot across the bow landlubber or just lubber bring a spring upon her cable jolly boat boatswain bucko.",
        3.64,
        3.96,
        4.83,
        3.57,
        3.25,
        4.03,
        "July 2020",
        10
    ),
    (
        "Jazmyn Peterson",
        "Jazmyn Peterson link",
        "Ye bilged on her anchor poop deck hang the jib coffer Sail ho Plate Fleet jolly boat barkadeer sheet. Gaff keelhaul cable sutler loot blow the man down crimp brigantine bowsprit Jolly Roger. Take a caulk scurvy coffer lugger run a shot across the bow landlubber or just lubber bring a spring upon her cable jolly boat boatswain bucko.",
        3.25,
        3.64,
        4.55,
        3.25,
        3.91,
        3.97,
        "April 2020",
        2
    ),
    (
        "Braylen Noble",
        "Braylen Noble link",
        "In that case I think that it is probable that no further steps may be taken. But if you are found again, then all must come out. I am sure, Mr. Holmes, that we are very much indebted to you for having cleared the matter up. I wish I knew how you reach your results.",
        3.14,
        3.91,
        3.64,
        4.03,
        4.57,
        3.64,
        "October 2020",
        12
    ),
    (
        "Jazmyn Peterson",
        "Jazmyn Peterson link",
        "Ulysses, Ulysses — Soaring through all the galaxies. In search of Earth, flying in to the night. Ulysses, Ulysses — Fighting evil and tyranny, with all his power, and with all of his might. Ulysses — no-one else can do the things you do. Ulysses — like a bolt of thunder from the blue. Ulysses — always fighting all the evil forces bringing peace and justice to all.",
        4.62,
        3.07,
        3.14,
        4.5,
        4.55,
        3.87,
        "July 2020",
        16
    ),
    (
        "Elaine Bauer",
        "Elaine Bauer link",
        "Barnaby The Bear’s my name, never call me Jack or James, I will sing my way to fame, Barnaby the Bear’s my name. Birds taught me to sing, when they took me to their king, first I had to fly, in the sky so high so high, so high so high so high, so — if you want to sing this way, think of what you’d like to say, add a tune and you will see, just how easy it can be. Treacle pudding, fish and chips, fizzy drinks and liquorice, flowers, rivers, sand and sea, snowflakes and the stars are free.",
        4.62,
        3.99,
        4.13,
        4.26,
        3.1,
        3.1,
        "July 2020",
        19
    ),
    (
        "Andrea Dean",
        "Andrea Dean link",
        "Cheese slices stinking bishop everyone loves. Everyone loves lancashire fromage boursin say cheese cheese triangles edam feta. Edam feta cut the cheese caerphilly the big cheese red leicester airedale edam. Mozzarella emmental ricotta fromage frais emmental cheeseburger fromage.",
        4.5,
        3.59,
        4.13,
        3.73,
        3.57,
        3.87,
        "July 2020",
        4
    ),
    (
        "Juliana Shepard",
        "Juliana Shepard link",
        "Esse deserunt shoulder t-bone. Non in qui bacon ipsum pastrami. Shankle lorem labore pork loin aliquip beef laboris ea qui jerky. Eu nostrud fatback meatloaf, burgdoggen pastrami drumstick elit lorem consequat ipsum. Pancetta sausage dolor cupidatat rump adipisicing pariatur burgdoggen voluptate aliqua.",
        4.26,
        4.67,
        3.57,
        3.1,
        3.25,
        4.02,
        "February 2020",
        15
    ),
    (
        "Reagan Boyer",
        "Reagan Boyer link",
        "Top Cat! The most effectual Top Cat! Who’s intellectual close friends get to call him T.C., providing it’s with dignity. Top Cat! The indisputable leader of the gang. He’s the boss, he’s a pip, he’s the championship. He’s the most tip top, Top Cat.",
        3.96,
        4.62,
        4.83,
        3.96,
        4.02,
        4.02,
        "August 2020",
        9
    ),
    (
        "Raphael Owens",
        "Raphael Owens link",
        "Beetroot water spinach okra water chestnut ricebean pea catsear courgette summer purslane. Water spinach arugula pea tatsoi aubergine spring onion bush tomato kale radicchio turnip chicory salsify pea sprouts fava bean. Dandelion zucchini burdock yarrow chickpea dandelion sorrel courgette turnip greens tigernut soybean radish artichoke wattle seed endive groundnut broccoli arugula.",
        3.25,
        3.07,
        4.63,
        3.73,
        3.57,
        4.57,
        "June 2020",
        2
    ),
    (
        "Reese Bautista",
        "Reese Bautista link",
        "Esse deserunt shoulder t-bone. Non in qui bacon ipsum pastrami. Shankle lorem labore pork loin aliquip beef laboris ea qui jerky. Eu nostrud fatback meatloaf, burgdoggen pastrami drumstick elit lorem consequat ipsum. Pancetta sausage dolor cupidatat rump adipisicing pariatur burgdoggen voluptate aliqua.",
        4.13,
        3.64,
        3.07,
        4.02,
        3.14,
        3.64,
        "February 2020",
        11
    ),
    (
        "Xander Mccann",
        "Xander Mccann link",
        "Barnaby The Bear’s my name, never call me Jack or James, I will sing my way to fame, Barnaby the Bear’s my name. Birds taught me to sing, when they took me to their king, first I had to fly, in the sky so high so high, so high so high so high, so — if you want to sing this way, think of what you’d like to say, add a tune and you will see, just how easy it can be. Treacle pudding, fish and chips, fizzy drinks and liquorice, flowers, rivers, sand and sea, snowflakes and the stars are free.",
        4.55,
        3.64,
        3.59,
        3.96,
        3.64,
        4.62,
        "March 2020",
        6
    ),
    (
        "Sanaa Bender",
        "Sanaa Bender link",
        "I had called upon my friend Sherlock Holmes upon the second morning after Christmas, with the intention of wishing him the compliments of the season. He was lounging upon the sofa in a purple dressing-gown, a pipe-rack within his reach upon the right, and a pile of crumpled morning papers, evidently newly studied, near at hand. Beside the couch was a wooden chair, and on the angle of the back hung a very seedy and disreputable hard-felt hat, much the worse for wear, and cracked in several places. A lens and a forceps lying upon the seat of the chair suggested that the hat had been suspended in this manner for the purpose of examination.",
        3.1,
        3.1,
        3.1,
        3.96,
        3.73,
        3.25,
        "February 2020",
        7
    ),
    (
        "Adam Burgess",
        "Adam Burgess link",
        "I do not know that there is anything else for me to explain. I was determined to preserve my disguise as long as possible, and hence my preference for a dirty face. Knowing that my wife would be terribly anxious, I slipped off my ring and confided it to the Lascar at a moment when no constable was watching me, together with a hurried scrawl, telling her that she had no cause to fear.",
        3.25,
        3.14,
        3.87,
        3.57,
        3.57,
        4.63,
        "September 2020",
        3
    ),
    (
        "Reagan Boyer",
        "Reagan Boyer link",
        "Barnaby The Bear’s my name, never call me Jack or James, I will sing my way to fame, Barnaby the Bear’s my name. Birds taught me to sing, when they took me to their king, first I had to fly, in the sky so high so high, so high so high so high, so — if you want to sing this way, think of what you’d like to say, add a tune and you will see, just how easy it can be. Treacle pudding, fish and chips, fizzy drinks and liquorice, flowers, rivers, sand and sea, snowflakes and the stars are free.",
        4.13,
        3.64,
        4.55,
        3.64,
        4.5,
        3.25,
        "June 2020",
        18
    ),
    (
        "Sanaa Bender",
        "Sanaa Bender link",
        "Stop talking, brain thinking. Hush. Aw, you're all Mr. Grumpy Face today. All I've got to do is pass as an ordinary human being. Simple. What could possibly go wrong? I'm the Doctor. Well, they call me the Doctor. I don't know why. I call me the Doctor too. I still don't know why.",
        3.97,
        3.1,
        3.99,
        4.03,
        4.13,
        4.03,
        "January 2020",
        7
    ),
    (
        "Alanna Durham",
        "Alanna Durham link",
        "Cheese slices stinking bishop everyone loves. Everyone loves lancashire fromage boursin say cheese cheese triangles edam feta. Edam feta cut the cheese caerphilly the big cheese red leicester airedale edam. Mozzarella emmental ricotta fromage frais emmental cheeseburger fromage.",
        3.1,
        4.5,
        3.59,
        4.62,
        4.13,
        4.67,
        "April 2020",
        1
    ),
    (
        "Elaine Bauer",
        "Elaine Bauer link",
        "80 days around the world, we’ll find a pot of gold just sitting where the rainbow’s ending. Time — we’ll fight against the time, and we’ll fly on the white wings of the wind. 80 days around the world, no we won’t say a word before the ship is really back. Round, round, all around the world. Round, all around the world. Round, all around the world. Round, all around the world.",
        4.55,
        3.14,
        3.97,
        3.1,
        3.64,
        3.1,
        "January 2020",
        9
    ),
    (
        "Ellie Gregory",
        "Ellie Gregory link",
        "Morbi a metus. Phasellus enim erat, vestibulum vel, aliquam a, posuere eu, velit. Nullam sapien sem, ornare ac, nonummy non, lobortis a, enim. Nunc tincidunt ante vitae massa. Duis ante orci, molestie vitae, vehicula venenatis, tincidunt ac, pede. Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Etiam commodo dui eget wisi. Donec iaculis gravida nulla. Donec quis nibh at felis congue commodo. Etiam bibendum elit eget erat.",
        3.73,
        3.96,
        3.57,
        3.97,
        3.1,
        3.59,
        "September 2020",
        14
    ),
    (
        "Adam Burgess",
        "Adam Burgess link",
        "Ye bilged on her anchor poop deck hang the jib coffer Sail ho Plate Fleet jolly boat barkadeer sheet. Gaff keelhaul cable sutler loot blow the man down crimp brigantine bowsprit Jolly Roger. Take a caulk scurvy coffer lugger run a shot across the bow landlubber or just lubber bring a spring upon her cable jolly boat boatswain bucko.",
        4.63,
        3.1,
        4.03,
        4.62,
        4.13,
        4.02,
        "October 2020",
        2
    ),
    (
        "Reese Bautista",
        "Reese Bautista link",
        "Pepper jack smelly cheese monterey jack. Feta cottage cheese paneer roquefort cheddar bocconcini cheesy feet pecorino. Mozzarella cow cheesecake cheddar st. agur blue cheese danish fontina cream cheese cheese on toast. Manchego say cheese cottage cheese cottage cheese taleggio cheese triangles.",
        3.25,
        3.99,
        4.67,
        4.57,
        3.59,
        4.57,
        "December 2020",
        7
    ),
    (
        "Giselle Henson",
        "Giselle Henson link",
        "80 days around the world, we’ll find a pot of gold just sitting where the rainbow’s ending. Time — we’ll fight against the time, and we’ll fly on the white wings of the wind. 80 days around the world, no we won’t say a word before the ship is really back. Round, round, all around the world. Round, all around the world. Round, all around the world. Round, all around the world.",
        3.91,
        3.57,
        4.55,
        4.67,
        3.91,
        3.91,
        "May 2020",
        14
    ),
    (
        "Gwendolyn Schultz",
        "Gwendolyn Schultz link",
        "Hong Kong Phooey, number one super guy. Hong Kong Phooey, quicker than the human eye. He’s got style, a groovy style, and a car that just won’t stop. When the going gets tough, he’s really rough, with a Hong Kong Phooey chop (Hi-Ya!). Hong Kong Phooey, number one super guy. Hong Kong Phooey, quicker than the human eye. Hong Kong Phooey, he’s fan-riffic!",
        4.5,
        3.25,
        3.97,
        4.5,
        3.64,
        3.64,
        "October 2020",
        6
    ),
    (
        "Adam Burgess",
        "Adam Burgess link",
        "There’s a voice that keeps on calling me. Down the road, that’s where I’ll always be. Every stop I make, I make a new friend. Can’t stay for long, just turn around and I’m gone again. Maybe tomorrow, I’ll want to settle down, Until tomorrow, I’ll just keep moving on.",
        4.83,
        3.14,
        4.62,
        3.1,
        4.62,
        3.64,
        "December 2020",
        16
    ),
    (
        "Demarion Munoz",
        "Demarion Munoz link",
        "Pepper jack smelly cheese monterey jack. Feta cottage cheese paneer roquefort cheddar bocconcini cheesy feet pecorino. Mozzarella cow cheesecake cheddar st. agur blue cheese danish fontina cream cheese cheese on toast. Manchego say cheese cottage cheese cottage cheese taleggio cheese triangles.",
        3.73,
        3.57,
        3.14,
        4.26,
        3.91,
        3.57,
        "March 2020",
        12
    ),
    (
        "Lindsay Knox",
        "Lindsay Knox link",
        "Pepper jack smelly cheese monterey jack. Feta cottage cheese paneer roquefort cheddar bocconcini cheesy feet pecorino. Mozzarella cow cheesecake cheddar st. agur blue cheese danish fontina cream cheese cheese on toast. Manchego say cheese cottage cheese cottage cheese taleggio cheese triangles.",
        3.14,
        3.96,
        3.25,
        3.25,
        3.25,
        3.99,
        "March 2020",
        13
    ),
    (
        "Jazmyn Peterson",
        "Jazmyn Peterson link",
        "There’s a voice that keeps on calling me. Down the road, that’s where I’ll always be. Every stop I make, I make a new friend. Can’t stay for long, just turn around and I’m gone again. Maybe tomorrow, I’ll want to settle down, Until tomorrow, I’ll just keep moving on.",
        4.26,
        3.14,
        4.83,
        3.87,
        3.64,
        4.63,
        "April 2020",
        1
    ),
    (
        "Marley Estes",
        "Marley Estes link",
        "Thundercats are on the move, Thundercats are loose. Feel the magic, hear the roar, Thundercats are loose. Thunder, thunder, thunder, Thundercats! Thunder, thunder, thunder, Thundercats! Thunder, thunder, thunder, Thundercats! Thunder, thunder, thunder, Thundercats! Thundercats!",
        4.55,
        4.55,
        3.73,
        3.25,
        3.25,
        3.91,
        "July 2020",
        14
    ),
    (
        "Billy Fox",
        "Billy Fox link",
        "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nullam feugiat, turpis at pulvinar vulputate, erat libero tristique tellus, nec bibendum odio risus sit amet ante. Aliquam erat volutpat. Nunc auctor. Mauris pretium quam et urna. Fusce nibh. Duis risus. Curabitur sagittis hendrerit ante. Aliquam erat volutpat. Vestibulum erat nulla, ullamcorper nec, rutrum non, nonummy ac, erat. Duis condimentum augue id magna semper rutrum. Nullam justo enim, consectetuer nec, ullamcorper ac, vestibulum in, elit. Proin pede metus, vulputate nec, fermentum fringilla, vehicula vitae, justo. Fusce consectetuer risus a nunc. Aliquam ornare wisi eu metus. Integer pellentesque quam vel velit. Duis pulvinar.",
        3.41,
        4.57,
        3.41,
        3.57,
        3.91,
        3.97,
        "May 2020",
        8
    ),
    (
        "Sanaa Bender",
        "Sanaa Bender link",
        "There’s a voice that keeps on calling me. Down the road, that’s where I’ll always be. Every stop I make, I make a new friend. Can’t stay for long, just turn around and I’m gone again. Maybe tomorrow, I’ll want to settle down, Until tomorrow, I’ll just keep moving on.",
        4.5,
        3.97,
        3.25,
        3.97,
        4.26,
        3.73,
        "April 2020",
        9
    ),
    (
        "Juliana Shepard",
        "Juliana Shepard link",
        "80 days around the world, we’ll find a pot of gold just sitting where the rainbow’s ending. Time — we’ll fight against the time, and we’ll fly on the white wings of the wind. 80 days around the world, no we won’t say a word before the ship is really back. Round, round, all around the world. Round, all around the world. Round, all around the world. Round, all around the world.",
        3.1,
        3.96,
        4.13,
        4.63,
        4.63,
        3.1,
        "April 2020",
        11
    ),
    (
        "Teagan Briggs",
        "Teagan Briggs link",
        "Ye bilged on her anchor poop deck hang the jib coffer Sail ho Plate Fleet jolly boat barkadeer sheet. Gaff keelhaul cable sutler loot blow the man down crimp brigantine bowsprit Jolly Roger. Take a caulk scurvy coffer lugger run a shot across the bow landlubber or just lubber bring a spring upon her cable jolly boat boatswain bucko.",
        4.5,
        3.87,
        4.03,
        3.14,
        3.91,
        4.55,
        "August 2020",
        16
    ),
    (
        "Reese Bautista",
        "Reese Bautista link",
        "Ye bilged on her anchor poop deck hang the jib coffer Sail ho Plate Fleet jolly boat barkadeer sheet. Gaff keelhaul cable sutler loot blow the man down crimp brigantine bowsprit Jolly Roger. Take a caulk scurvy coffer lugger run a shot across the bow landlubber or just lubber bring a spring upon her cable jolly boat boatswain bucko.",
        3.1,
        3.64,
        3.57,
        4.26,
        3.14,
        4.02,
        "September 2020",
        18
    ),
    (
        "Juliana Shepard",
        "Juliana Shepard link",
        "Knight Rider, a shadowy flight into the dangerous world of a man who does not exist. Michael Knight, a young loner on a crusade to champion the cause of the innocent, the helpless in a world of criminals who operate above the law.",
        3.64,
        3.41,
        4.03,
        3.59,
        3.73,
        3.1,
        "May 2020",
        3
    ),
    (
        "Jazmyn Peterson",
        "Jazmyn Peterson link",
        "There’s a voice that keeps on calling me. Down the road, that’s where I’ll always be. Every stop I make, I make a new friend. Can’t stay for long, just turn around and I’m gone again. Maybe tomorrow, I’ll want to settle down, Until tomorrow, I’ll just keep moving on.",
        4.02,
        3.59,
        3.64,
        4.67,
        4.63,
        3.25,
        "November 2020",
        11
    ),
    (
        "Tyrell Burns",
        "Tyrell Burns link",
        "Pommy ipsum bog off mush, apple and pears laughing gear. Bad Wolf one off Shakespeare made a pig's ear of it the dog's dinner fish and chips absobloodylootely, they can sod off a bit miffed conked him one on the nose it's me peepers see a man about a dog blimey is she 'avin a laugh, crumpets have a butcher's at this a cracking fork out absolute. Tally-ho well fit Northeners twiglets grub's up what a load of guff spend a penny, a right toff pork dripping cockney cup of tea. Jolly good odds and sods ponce upper class got a lot of brass gob hedgehog double dutch, ponce hedgehog fancy a cuppa spiffing throw a paddy cockney.",
        3.07,
        4.62,
        3.1,
        4.57,
        3.14,
        4.67,
        "August 2020",
        2
    ),
    (
        "Emmy Armstrong",
        "Emmy Armstrong link",
        "Gumbo beet greens corn soko endive gumbo gourd. Parsley shallot courgette tatsoi pea sprouts fava bean collard greens dandelion okra wakame tomato. Dandelion cucumber earthnut pea peanut soko zucchini.",
        3.14,
        4.62,
        3.59,
        4.55,
        4.13,
        4.63,
        "August 2020",
        5
    ),
    (
        "Sanaa Bender",
        "Sanaa Bender link",
        "Knight Rider, a shadowy flight into the dangerous world of a man who does not exist. Michael Knight, a young loner on a crusade to champion the cause of the innocent, the helpless in a world of criminals who operate above the law.",
        3.59,
        4.63,
        3.64,
        4.55,
        3.1,
        4.57,
        "May 2020",
        7
    ),
    (
        "Tyrell Burns",
        "Tyrell Burns link",
        "80 days around the world, we’ll find a pot of gold just sitting where the rainbow’s ending. Time — we’ll fight against the time, and we’ll fly on the white wings of the wind. 80 days around the world, no we won’t say a word before the ship is really back. Round, round, all around the world. Round, all around the world. Round, all around the world. Round, all around the world.",
        4.55,
        3.73,
        3.73,
        4.13,
        4.83,
        4.63,
        "February 2020",
        7
    ),
    (
        "Reese Bautista",
        "Reese Bautista link",
        "Gumbo beet greens corn soko endive gumbo gourd. Parsley shallot courgette tatsoi pea sprouts fava bean collard greens dandelion okra wakame tomato. Dandelion cucumber earthnut pea peanut soko zucchini.",
        4.03,
        3.59,
        4.13,
        3.64,
        3.87,
        3.96,
        "January 2020",
        13
    ),
    (
        "Billy Fox",
        "Billy Fox link",
        "Barnaby The Bear’s my name, never call me Jack or James, I will sing my way to fame, Barnaby the Bear’s my name. Birds taught me to sing, when they took me to their king, first I had to fly, in the sky so high so high, so high so high so high, so — if you want to sing this way, think of what you’d like to say, add a tune and you will see, just how easy it can be. Treacle pudding, fish and chips, fizzy drinks and liquorice, flowers, rivers, sand and sea, snowflakes and the stars are free.",
        3.1,
        3.07,
        3.73,
        3.14,
        3.97,
        4.55,
        "October 2020",
        1
    ),
    (
        "Reese Bautista",
        "Reese Bautista link",
        "I had called upon my friend Sherlock Holmes upon the second morning after Christmas, with the intention of wishing him the compliments of the season. He was lounging upon the sofa in a purple dressing-gown, a pipe-rack within his reach upon the right, and a pile of crumpled morning papers, evidently newly studied, near at hand. Beside the couch was a wooden chair, and on the angle of the back hung a very seedy and disreputable hard-felt hat, much the worse for wear, and cracked in several places. A lens and a forceps lying upon the seat of the chair suggested that the hat had been suspended in this manner for the purpose of examination.",
        4.63,
        3.57,
        3.99,
        3.99,
        3.87,
        3.41,
        "January 2020",
        17
    ),
    (
        "Jaylin Ruiz",
        "Jaylin Ruiz link",
        "Esse deserunt shoulder t-bone. Non in qui bacon ipsum pastrami. Shankle lorem labore pork loin aliquip beef laboris ea qui jerky. Eu nostrud fatback meatloaf, burgdoggen pastrami drumstick elit lorem consequat ipsum. Pancetta sausage dolor cupidatat rump adipisicing pariatur burgdoggen voluptate aliqua.",
        3.1,
        4.62,
        3.64,
        3.41,
        3.73,
        3.64,
        "July 2020",
        11
    ),
    (
        "Tyrell Burns",
        "Tyrell Burns link",
        "Kid, I've flown from one side of this galaxy to the other. I've seen a lot of strange stuff, but I've never seen anything to make me believe there's one all-powerful Force controlling everything. There's no mystical energy field that controls my destiny. It's all a lot of simple tricks and nonsense. Kid, I've flown from one side of this galaxy to the other. I've seen a lot of strange stuff, but I've never seen anything to make me believe there's one all-powerful Force controlling everything. There's no mystical energy field that controls my destiny. It's all a lot of simple tricks and nonsense.",
        3.59,
        3.99,
        4.13,
        3.99,
        3.25,
        3.91,
        "July 2020",
        3
    ),
    (
        "Reese Bautista",
        "Reese Bautista link",
        "Beetroot water spinach okra water chestnut ricebean pea catsear courgette summer purslane. Water spinach arugula pea tatsoi aubergine spring onion bush tomato kale radicchio turnip chicory salsify pea sprouts fava bean. Dandelion zucchini burdock yarrow chickpea dandelion sorrel courgette turnip greens tigernut soybean radish artichoke wattle seed endive groundnut broccoli arugula.",
        4.57,
        3.57,
        3.57,
        4.83,
        3.64,
        3.1,
        "November 2020",
        8
    ),
    (
        "Marley Estes",
        "Marley Estes link",
        "In that case I think that it is probable that no further steps may be taken. But if you are found again, then all must come out. I am sure, Mr. Holmes, that we are very much indebted to you for having cleared the matter up. I wish I knew how you reach your results.",
        3.96,
        3.91,
        4.13,
        4.02,
        3.07,
        4.03,
        "October 2020",
        17
    ),
    (
        "Billy Fox",
        "Billy Fox link",
        "Pepper jack smelly cheese monterey jack. Feta cottage cheese paneer roquefort cheddar bocconcini cheesy feet pecorino. Mozzarella cow cheesecake cheddar st. agur blue cheese danish fontina cream cheese cheese on toast. Manchego say cheese cottage cheese cottage cheese taleggio cheese triangles.",
        4.57,
        3.64,
        3.64,
        3.07,
        4.62,
        3.73,
        "March 2020",
        18
    ),
    (
        "Victor Skinner",
        "Victor Skinner link",
        "Beetroot water spinach okra water chestnut ricebean pea catsear courgette summer purslane. Water spinach arugula pea tatsoi aubergine spring onion bush tomato kale radicchio turnip chicory salsify pea sprouts fava bean. Dandelion zucchini burdock yarrow chickpea dandelion sorrel courgette turnip greens tigernut soybean radish artichoke wattle seed endive groundnut broccoli arugula.",
        4.5,
        3.73,
        4.63,
        3.41,
        3.59,
        3.07,
        "October 2020",
        16
    ),
    (
        "Juliana Shepard",
        "Juliana Shepard link",
        "Pommy ipsum bog off mush, apple and pears laughing gear. Bad Wolf one off Shakespeare made a pig's ear of it the dog's dinner fish and chips absobloodylootely, they can sod off a bit miffed conked him one on the nose it's me peepers see a man about a dog blimey is she 'avin a laugh, crumpets have a butcher's at this a cracking fork out absolute. Tally-ho well fit Northeners twiglets grub's up what a load of guff spend a penny, a right toff pork dripping cockney cup of tea. Jolly good odds and sods ponce upper class got a lot of brass gob hedgehog double dutch, ponce hedgehog fancy a cuppa spiffing throw a paddy cockney.",
        3.59,
        4.03,
        4.83,
        4.03,
        3.07,
        4.02,
        "November 2020",
        8
    ),
    (
        "Rachael Foley",
        "Rachael Foley link",
        "I do not know that there is anything else for me to explain. I was determined to preserve my disguise as long as possible, and hence my preference for a dirty face. Knowing that my wife would be terribly anxious, I slipped off my ring and confided it to the Lascar at a moment when no constable was watching me, together with a hurried scrawl, telling her that she had no cause to fear.",
        3.64,
        4.03,
        3.1,
        4.62,
        4.83,
        4.26,
        "September 2020",
        2
    ),
    (
        "Gwendolyn Schultz",
        "Gwendolyn Schultz link",
        "Wait a minute - you've been declared dead. You can't give orders around here. Flair is what marks the difference between artistry and mere competence. Your shields were failing, sir. Wouldn't that bring about chaos? Could someone survive inside a transporter buffer for 75 years? I recommend you don't fire until you're within 40,000 kilometers. Computer, belay that order. This should be interesting. Maybe if we felt any human loss as keenly as we feel one of those close to us, human history would be far less bloody.",
        3.25,
        4.13,
        3.91,
        4.26,
        3.99,
        4.5,
        "August 2020",
        12
    ),
    (
        "Adam Burgess",
        "Adam Burgess link",
        "Esse deserunt shoulder t-bone. Non in qui bacon ipsum pastrami. Shankle lorem labore pork loin aliquip beef laboris ea qui jerky. Eu nostrud fatback meatloaf, burgdoggen pastrami drumstick elit lorem consequat ipsum. Pancetta sausage dolor cupidatat rump adipisicing pariatur burgdoggen voluptate aliqua.",
        4.03,
        3.96,
        4.57,
        4.02,
        4.26,
        3.1,
        "June 2020",
        18
    ),
    (
        "Elaine Bauer",
        "Elaine Bauer link",
        "Pepper jack smelly cheese monterey jack. Feta cottage cheese paneer roquefort cheddar bocconcini cheesy feet pecorino. Mozzarella cow cheesecake cheddar st. agur blue cheese danish fontina cream cheese cheese on toast. Manchego say cheese cottage cheese cottage cheese taleggio cheese triangles.",
        3.57,
        3.1,
        4.67,
        3.1,
        3.25,
        3.25,
        "May 2020",
        18
    ),
    (
        "Lindsay Knox",
        "Lindsay Knox link",
        "Gumbo beet greens corn soko endive gumbo gourd. Parsley shallot courgette tatsoi pea sprouts fava bean collard greens dandelion okra wakame tomato. Dandelion cucumber earthnut pea peanut soko zucchini.",
        3.64,
        3.25,
        3.25,
        3.57,
        3.1,
        3.87,
        "April 2020",
        17
    ),
    (
        "Juliana Shepard",
        "Juliana Shepard link",
        "Cheese slices stinking bishop everyone loves. Everyone loves lancashire fromage boursin say cheese cheese triangles edam feta. Edam feta cut the cheese caerphilly the big cheese red leicester airedale edam. Mozzarella emmental ricotta fromage frais emmental cheeseburger fromage.",
        3.25,
        3.73,
        3.57,
        3.59,
        3.59,
        3.99,
        "October 2020",
        5
    ),
    (
        "Adam Burgess",
        "Adam Burgess link",
        "Boom grapple parrel fire in the hole Sink me fluke ye jury mast spanker gangplank. Weigh anchor belaying pin log list topgallant grapple code of conduct rutters Chain Shot hang the jib. Me lee squiffy rum rutters yardarm Gold Road Barbary Coast carouser Plate Fleet.",
        4.5,
        3.07,
        3.07,
        4.62,
        3.87,
        4.5,
        "June 2020",
        5
    ),
    (
        "Demarion Munoz",
        "Demarion Munoz link",
        "Pommy ipsum bog off mush, apple and pears laughing gear. Bad Wolf one off Shakespeare made a pig's ear of it the dog's dinner fish and chips absobloodylootely, they can sod off a bit miffed conked him one on the nose it's me peepers see a man about a dog blimey is she 'avin a laugh, crumpets have a butcher's at this a cracking fork out absolute. Tally-ho well fit Northeners twiglets grub's up what a load of guff spend a penny, a right toff pork dripping cockney cup of tea. Jolly good odds and sods ponce upper class got a lot of brass gob hedgehog double dutch, ponce hedgehog fancy a cuppa spiffing throw a paddy cockney.",
        4.67,
        3.64,
        4.26,
        3.25,
        4.02,
        4.57,
        "March 2020",
        10
    ),
    (
        "Juliana Shepard",
        "Juliana Shepard link",
        "Gumbo beet greens corn soko endive gumbo gourd. Parsley shallot courgette tatsoi pea sprouts fava bean collard greens dandelion okra wakame tomato. Dandelion cucumber earthnut pea peanut soko zucchini.",
        3.1,
        3.25,
        3.41,
        4.63,
        3.91,
        3.25,
        "July 2020",
        8
    ),
    (
        "Jaylin Ruiz",
        "Jaylin Ruiz link",
        "I had called upon my friend Sherlock Holmes upon the second morning after Christmas, with the intention of wishing him the compliments of the season. He was lounging upon the sofa in a purple dressing-gown, a pipe-rack within his reach upon the right, and a pile of crumpled morning papers, evidently newly studied, near at hand. Beside the couch was a wooden chair, and on the angle of the back hung a very seedy and disreputable hard-felt hat, much the worse for wear, and cracked in several places. A lens and a forceps lying upon the seat of the chair suggested that the hat had been suspended in this manner for the purpose of examination.",
        3.64,
        4.57,
        4.02,
        3.41,
        4.62,
        3.91,
        "March 2020",
        2
    ),
    (
        "Emmy Armstrong",
        "Emmy Armstrong link",
        "Top Cat! The most effectual Top Cat! Who’s intellectual close friends get to call him T.C., providing it’s with dignity. Top Cat! The indisputable leader of the gang. He’s the boss, he’s a pip, he’s the championship. He’s the most tip top, Top Cat.",
        3.25,
        3.07,
        3.14,
        3.87,
        3.64,
        4.57,
        "August 2020",
        1
    ),
    (
        "Braelyn Gibson",
        "Braelyn Gibson link",
        "Knight Rider, a shadowy flight into the dangerous world of a man who does not exist. Michael Knight, a young loner on a crusade to champion the cause of the innocent, the helpless in a world of criminals who operate above the law.",
        4.55,
        3.96,
        4.03,
        3.1,
        3.73,
        3.96,
        "November 2020",
        2
    ),
    (
        "Jazmyn Peterson",
        "Jazmyn Peterson link",
        "Ulysses, Ulysses — Soaring through all the galaxies. In search of Earth, flying in to the night. Ulysses, Ulysses — Fighting evil and tyranny, with all his power, and with all of his might. Ulysses — no-one else can do the things you do. Ulysses — like a bolt of thunder from the blue. Ulysses — always fighting all the evil forces bringing peace and justice to all.",
        3.87,
        3.59,
        3.1,
        4.02,
        4.5,
        4.03,
        "March 2020",
        11
    ),
    (
        "Braylen Noble",
        "Braylen Noble link",
        "In that case I think that it is probable that no further steps may be taken. But if you are found again, then all must come out. I am sure, Mr. Holmes, that we are very much indebted to you for having cleared the matter up. I wish I knew how you reach your results.",
        3.91,
        4.03,
        4.26,
        3.64,
        3.99,
        4.02,
        "May 2020",
        17
    ),
    (
        "Andrea Dean",
        "Andrea Dean link",
        "Mutley, you snickering, floppy eared hound. When courage is needed, you’re never around. Those medals you wear on your moth-eaten chest should be there for bungling at which you are best. So, stop that pigeon, stop that pigeon, stop that pigeon, stop that pigeon, stop that pigeon, stop that pigeon, stop that pigeon. Howwww! Nab him, jab him, tab him, grab him, stop that pigeon now.",
        3.87,
        3.25,
        3.1,
        3.73,
        4.55,
        4.62,
        "November 2020",
        16
    ),
    (
        "Adam Burgess",
        "Adam Burgess link",
        "Beetroot water spinach okra water chestnut ricebean pea catsear courgette summer purslane. Water spinach arugula pea tatsoi aubergine spring onion bush tomato kale radicchio turnip chicory salsify pea sprouts fava bean. Dandelion zucchini burdock yarrow chickpea dandelion sorrel courgette turnip greens tigernut soybean radish artichoke wattle seed endive groundnut broccoli arugula.",
        3.99,
        4.5,
        3.73,
        3.91,
        4.5,
        3.97,
        "November 2020",
        5
    ),
    (
        "Victor Skinner",
        "Victor Skinner link",
        "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nullam feugiat, turpis at pulvinar vulputate, erat libero tristique tellus, nec bibendum odio risus sit amet ante. Aliquam erat volutpat. Nunc auctor. Mauris pretium quam et urna. Fusce nibh. Duis risus. Curabitur sagittis hendrerit ante. Aliquam erat volutpat. Vestibulum erat nulla, ullamcorper nec, rutrum non, nonummy ac, erat. Duis condimentum augue id magna semper rutrum. Nullam justo enim, consectetuer nec, ullamcorper ac, vestibulum in, elit. Proin pede metus, vulputate nec, fermentum fringilla, vehicula vitae, justo. Fusce consectetuer risus a nunc. Aliquam ornare wisi eu metus. Integer pellentesque quam vel velit. Duis pulvinar.",
        3.99,
        3.14,
        3.07,
        3.25,
        3.07,
        4.83,
        "May 2020",
        2
    ),
    (
        "Demarion Munoz",
        "Demarion Munoz link",
        "Morbi a metus. Phasellus enim erat, vestibulum vel, aliquam a, posuere eu, velit. Nullam sapien sem, ornare ac, nonummy non, lobortis a, enim. Nunc tincidunt ante vitae massa. Duis ante orci, molestie vitae, vehicula venenatis, tincidunt ac, pede. Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Etiam commodo dui eget wisi. Donec iaculis gravida nulla. Donec quis nibh at felis congue commodo. Etiam bibendum elit eget erat.",
        3.14,
        3.96,
        4.83,
        4.55,
        3.91,
        3.97,
        "September 2020",
        13
    ),
    (
        "Andrea Dean",
        "Andrea Dean link",
        "Pommy ipsum bog off mush, apple and pears laughing gear. Bad Wolf one off Shakespeare made a pig's ear of it the dog's dinner fish and chips absobloodylootely, they can sod off a bit miffed conked him one on the nose it's me peepers see a man about a dog blimey is she 'avin a laugh, crumpets have a butcher's at this a cracking fork out absolute. Tally-ho well fit Northeners twiglets grub's up what a load of guff spend a penny, a right toff pork dripping cockney cup of tea. Jolly good odds and sods ponce upper class got a lot of brass gob hedgehog double dutch, ponce hedgehog fancy a cuppa spiffing throw a paddy cockney.",
        3.59,
        3.73,
        4.83,
        4.13,
        4.13,
        3.87,
        "March 2020",
        1
    ),
    (
        "Emmy Armstrong",
        "Emmy Armstrong link",
        "There’s a voice that keeps on calling me. Down the road, that’s where I’ll always be. Every stop I make, I make a new friend. Can’t stay for long, just turn around and I’m gone again. Maybe tomorrow, I’ll want to settle down, Until tomorrow, I’ll just keep moving on.",
        3.1,
        4.57,
        4.03,
        4.67,
        3.25,
        3.99,
        "December 2020",
        19
    ),
    (
        "Adam Burgess",
        "Adam Burgess link",
        "One for all and all for one, Muskehounds are always ready. One for all and all for one, helping everybody. One for all and all for one, it’s a pretty story. Sharing everything with fun, that’s the way to be. One for all and all for one, Muskehounds are always ready. One for all and all for one, helping everybody. One for all and all for one, can sound pretty corny. If you’ve got a problem chum, think how it could be.",
        3.97,
        4.62,
        3.41,
        3.64,
        3.14,
        3.64,
        "January 2020",
        10
    );