CREATE TABLE locations (
    id bigint not null auto_increment,
    title varchar(50) NOT NULL,
    street varchar(70),
    city varchar(30),
    state_territory varchar(30),
    country varchar(30) NOT NULL,
    zip int(5),
    international boolean,
    rating decimal NOT NULL,
    numberofratings int NOT NULL,
    superhost boolean NOT NULL,
    price decimal NOT NULL,
    host varchar(50) NOT NULL,
    guests int NOT NULL,
    beds int NOT NULL,
    bedrooms int NOT NULL,
    bathrooms int NOT NULL,
    primary key(id)
);
